name: SuperPoderes
version: '1.0-SNAPSHOT'
main: me.guss.curso.Curso
api-version: '1.18'
description: 'Plugin de Super Poderes - Comandos e eventos inovadores em português!'
author: 'Guss'
website: 'https://github.com/guss'

commands:
  superpoder:
    description: 'Comando principal dos super poderes'
    usage: '/superpoder <poder> [jogador]'
    aliases: [sp, poder]
  voar:
    description: 'Permite voar pelo servidor'
    usage: '/voar [jogador]'
    aliases: [fly]
  teletransporte:
    description: 'Teletransporta para um jogador'
    usage: '/teletransporte <jogador>'
    aliases: [tp, teleport]
  raio:
    description: 'Invoca um raio no local'
    usage: '/raio [jogador]'
    aliases: [lightning]
  explosao:
    description: 'Cria uma explosão controlada'
    usage: '/explosao [força]'
    aliases: [explode, boom]
  cura:
    description: 'Cura um jogador'
    usage: '/cura [jogador]'
    aliases: [heal]
  velocidade:
    description: 'Altera a velocidade de movimento'
    usage: '/velocidade <nível> [jogador]'
    aliases: [speed]
  invisibilidade:
    description: 'Torna um jogador invisível'
    usage: '/invisibilidade [jogador]'
    aliases: [invis, invisivel]

permissions:
  superpoderes.admin:
    description: 'Permissão de administrador'
    default: op
  superpoderes.voar:
    description: 'Permissão para voar'
    default: true
  superpoderes.teletransporte:
    description: 'Permissão para teletransporte'
    default: true
  superpoderes.raio:
    description: 'Permissão para invocar raios'
    default: op
  superpoderes.explosao:
    description: 'Permissão para criar explosões'
    default: op
  superpoderes.cura:
    description: 'Permissão para curar'
    default: true
  superpoderes.velocidade:
    description: 'Permissão para alterar velocidade'
    default: true
  superpoderes.invisibilidade:
    description: 'Permissão para invisibilidade'
    default: op
